/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteImport } from './routes/_main'
import { Route as SplashscreenIndexRouteImport } from './routes/splashscreen/index'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as SplashscreenCrashIndexRouteImport } from './routes/splashscreen/crash/index'
import { Route as PublicAuthIndexRouteImport } from './routes/public/auth/index'
import { Route as MainWatchIndexRouteImport } from './routes/_main/watch/index'
import { Route as MainSettingsIndexRouteImport } from './routes/_main/settings/index'
import { Route as MainSearchIndexRouteImport } from './routes/_main/search/index'
import { Route as MainProfilesIndexRouteImport } from './routes/_main/profiles/index'

const ScanLogViewerIndexLazyRouteImport = createFileRoute('/scan-log-viewer/')()
const IssueReportIndexLazyRouteImport = createFileRoute('/issue-report/')()
const DocsIndexLazyRouteImport = createFileRoute('/docs/')()
const MainListsIndexLazyRouteImport = createFileRoute('/_main/lists/')()

const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanLogViewerIndexLazyRoute = ScanLogViewerIndexLazyRouteImport.update({
  id: '/scan-log-viewer/',
  path: '/scan-log-viewer/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/scan-log-viewer/index.lazy').then((d) => d.Route),
)
const IssueReportIndexLazyRoute = IssueReportIndexLazyRouteImport.update({
  id: '/issue-report/',
  path: '/issue-report/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/issue-report/index.lazy').then((d) => d.Route),
)
const DocsIndexLazyRoute = DocsIndexLazyRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/docs/index.lazy').then((d) => d.Route))
const SplashscreenIndexRoute = SplashscreenIndexRouteImport.update({
  id: '/splashscreen/',
  path: '/splashscreen/',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const MainListsIndexLazyRoute = MainListsIndexLazyRouteImport.update({
  id: '/lists/',
  path: '/lists/',
  getParentRoute: () => MainRoute,
} as any).lazy(() =>
  import('./routes/_main/lists/index.lazy').then((d) => d.Route),
)
const SplashscreenCrashIndexRoute = SplashscreenCrashIndexRouteImport.update({
  id: '/splashscreen/crash/',
  path: '/splashscreen/crash/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicAuthIndexRoute = PublicAuthIndexRouteImport.update({
  id: '/public/auth/',
  path: '/public/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const MainWatchIndexRoute = MainWatchIndexRouteImport.update({
  id: '/watch/',
  path: '/watch/',
  getParentRoute: () => MainRoute,
} as any)
const MainSettingsIndexRoute = MainSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => MainRoute,
} as any).lazy(() =>
  import('./routes/_main/settings/index.lazy').then((d) => d.Route),
)
const MainSearchIndexRoute = MainSearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => MainRoute,
} as any).lazy(() =>
  import('./routes/_main/search/index.lazy').then((d) => d.Route),
)
const MainProfilesIndexRoute = MainProfilesIndexRouteImport.update({
  id: '/profiles/',
  path: '/profiles/',
  getParentRoute: () => MainRoute,
} as any).lazy(() =>
  import('./routes/_main/profiles/index.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/splashscreen/': typeof SplashscreenIndexRoute
  '/docs/': typeof DocsIndexLazyRoute
  '/issue-report/': typeof IssueReportIndexLazyRoute
  '/scan-log-viewer/': typeof ScanLogViewerIndexLazyRoute
  '/profiles/': typeof MainProfilesIndexRoute
  '/search/': typeof MainSearchIndexRoute
  '/settings/': typeof MainSettingsIndexRoute
  '/watch/': typeof MainWatchIndexRoute
  '/public/auth/': typeof PublicAuthIndexRoute
  '/splashscreen/crash/': typeof SplashscreenCrashIndexRoute
  '/lists/': typeof MainListsIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof MainIndexRoute
  '/splashscreen': typeof SplashscreenIndexRoute
  '/docs': typeof DocsIndexLazyRoute
  '/issue-report': typeof IssueReportIndexLazyRoute
  '/scan-log-viewer': typeof ScanLogViewerIndexLazyRoute
  '/profiles': typeof MainProfilesIndexRoute
  '/search': typeof MainSearchIndexRoute
  '/settings': typeof MainSettingsIndexRoute
  '/watch': typeof MainWatchIndexRoute
  '/public/auth': typeof PublicAuthIndexRoute
  '/splashscreen/crash': typeof SplashscreenCrashIndexRoute
  '/lists': typeof MainListsIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteWithChildren
  '/_main/': typeof MainIndexRoute
  '/splashscreen/': typeof SplashscreenIndexRoute
  '/docs/': typeof DocsIndexLazyRoute
  '/issue-report/': typeof IssueReportIndexLazyRoute
  '/scan-log-viewer/': typeof ScanLogViewerIndexLazyRoute
  '/_main/profiles/': typeof MainProfilesIndexRoute
  '/_main/search/': typeof MainSearchIndexRoute
  '/_main/settings/': typeof MainSettingsIndexRoute
  '/_main/watch/': typeof MainWatchIndexRoute
  '/public/auth/': typeof PublicAuthIndexRoute
  '/splashscreen/crash/': typeof SplashscreenCrashIndexRoute
  '/_main/lists/': typeof MainListsIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/splashscreen/'
    | '/docs/'
    | '/issue-report/'
    | '/scan-log-viewer/'
    | '/profiles/'
    | '/search/'
    | '/settings/'
    | '/watch/'
    | '/public/auth/'
    | '/splashscreen/crash/'
    | '/lists/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/splashscreen'
    | '/docs'
    | '/issue-report'
    | '/scan-log-viewer'
    | '/profiles'
    | '/search'
    | '/settings'
    | '/watch'
    | '/public/auth'
    | '/splashscreen/crash'
    | '/lists'
  id:
    | '__root__'
    | '/_main'
    | '/_main/'
    | '/splashscreen/'
    | '/docs/'
    | '/issue-report/'
    | '/scan-log-viewer/'
    | '/_main/profiles/'
    | '/_main/search/'
    | '/_main/settings/'
    | '/_main/watch/'
    | '/public/auth/'
    | '/splashscreen/crash/'
    | '/_main/lists/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren
  SplashscreenIndexRoute: typeof SplashscreenIndexRoute
  DocsIndexLazyRoute: typeof DocsIndexLazyRoute
  IssueReportIndexLazyRoute: typeof IssueReportIndexLazyRoute
  ScanLogViewerIndexLazyRoute: typeof ScanLogViewerIndexLazyRoute
  PublicAuthIndexRoute: typeof PublicAuthIndexRoute
  SplashscreenCrashIndexRoute: typeof SplashscreenCrashIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan-log-viewer/': {
      id: '/scan-log-viewer/'
      path: '/scan-log-viewer'
      fullPath: '/scan-log-viewer/'
      preLoaderRoute: typeof ScanLogViewerIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issue-report/': {
      id: '/issue-report/'
      path: '/issue-report'
      fullPath: '/issue-report/'
      preLoaderRoute: typeof IssueReportIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/splashscreen/': {
      id: '/splashscreen/'
      path: '/splashscreen'
      fullPath: '/splashscreen/'
      preLoaderRoute: typeof SplashscreenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/lists/': {
      id: '/_main/lists/'
      path: '/lists'
      fullPath: '/lists/'
      preLoaderRoute: typeof MainListsIndexLazyRouteImport
      parentRoute: typeof MainRoute
    }
    '/splashscreen/crash/': {
      id: '/splashscreen/crash/'
      path: '/splashscreen/crash'
      fullPath: '/splashscreen/crash/'
      preLoaderRoute: typeof SplashscreenCrashIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public/auth/': {
      id: '/public/auth/'
      path: '/public/auth'
      fullPath: '/public/auth/'
      preLoaderRoute: typeof PublicAuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/watch/': {
      id: '/_main/watch/'
      path: '/watch'
      fullPath: '/watch/'
      preLoaderRoute: typeof MainWatchIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/settings/': {
      id: '/_main/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof MainSettingsIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/search/': {
      id: '/_main/search/'
      path: '/search'
      fullPath: '/search/'
      preLoaderRoute: typeof MainSearchIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/profiles/': {
      id: '/_main/profiles/'
      path: '/profiles'
      fullPath: '/profiles/'
      preLoaderRoute: typeof MainProfilesIndexRouteImport
      parentRoute: typeof MainRoute
    }
  }
}

interface MainRouteChildren {
  MainIndexRoute: typeof MainIndexRoute
  MainProfilesIndexRoute: typeof MainProfilesIndexRoute
  MainSearchIndexRoute: typeof MainSearchIndexRoute
  MainSettingsIndexRoute: typeof MainSettingsIndexRoute
  MainWatchIndexRoute: typeof MainWatchIndexRoute
  MainListsIndexLazyRoute: typeof MainListsIndexLazyRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainIndexRoute: MainIndexRoute,
  MainProfilesIndexRoute: MainProfilesIndexRoute,
  MainSearchIndexRoute: MainSearchIndexRoute,
  MainSettingsIndexRoute: MainSettingsIndexRoute,
  MainWatchIndexRoute: MainWatchIndexRoute,
  MainListsIndexLazyRoute: MainListsIndexLazyRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
  SplashscreenIndexRoute: SplashscreenIndexRoute,
  DocsIndexLazyRoute: DocsIndexLazyRoute,
  IssueReportIndexLazyRoute: IssueReportIndexLazyRoute,
  ScanLogViewerIndexLazyRoute: ScanLogViewerIndexLazyRoute,
  PublicAuthIndexRoute: PublicAuthIndexRoute,
  SplashscreenCrashIndexRoute: SplashscreenCrashIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
